### ISSUE TITLE
ERROR 2 No such file or directory:

### ISSUE THREAD

**Issue by Mohamed3sam** [MehmetOKUYAR/Vehicles-Counting--Tracking-and-Speed-Estimation-with-YOLOv7-DeepSORT-Object-Tracking-and-Zone-Count#1]
[Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

**Comment by MehmetOKUYAR** [comment]
you can download DeepSORT again ----> 
[DeepSORT](https://drive.google.com/drive/folders/1kna8eWGrSfzaR6DtNJ8_GchGgPMv3VC8?usp=sharing)
because a part is missing
